SELECT
    IF(7 < g.GRADE, s.NAME, NULL),
    g.GRADE,
    s.MARKS
FROM
    STUDENTS s
    INNER JOIN GRADES g ON s.MARKS BETWEEN g.MIN_MARK AND g.MAX_MARK
ORDER BY
    g.GRADE DESC, s.NAME, s.MARKS;
